### ISSUE TITLE
Разработка пользовательского сценария 

### ISSUE THREAD

**Issue by GSkoba** [baltic-guys/read-path#14]
Создать модуль doc в который прописать пользовательский сценарий

**Comment by AleksandrKovalev186** [comment]
**Регистрация/Вход Пользователя в приложение**

**Регистрация пользователя(Логина и почты  нет в базе)**
Дано: Пользователь (которые еще не зарегистрирован)
Когда: Пользователь вводит на форме логин, пароль почту и нажимает кнопку Регистрация
Тогда: открывается страница стартовая страница, с предложением добавить книгу

**Вход зарегистрированного пользователя**
Дано: Пользователь (который зарегистрирован)
Когда: Пользователь Вводит логин и пароль и нажимает кнопку Продолжения
Тогда: Открывается страница с его книгами(если они были добавлены, если нет то с предложением добавить книгу)

**Вход незарегистрированного пользователя (Нет логина и почты в базе)**
Дано: Пользователь (незарегистрированный)
Когда: Пользователь вводит логин и пароль и нажимает кнопку Продолжения
Тогда: Появляется всплывающее окно «Вы не зарегистрированы в системе, пожалуйста проверьте логин и пароль, или зарегестрируйтесь» с кнопкой ОК

**Регистрация пользователя с почтой которая есть в системе**
Дано: Пользователь Почта которого есть в бд
Когда: Пользователь вводит логин, почту и пароль и нажимает кнопку регистрация
Тогда: Появляется всплывающее окно «Уважаемый пользователь, к сожалению такая почта уже есть в системе, используйте другой почтовый ящик» с кнопкой ОК

**Регистрация пользователя с логином который есть в системе** 
Дано: Пользователь нас странице регистрации
Когда:  Пользователь вводит логин, почту и пароль и нажимает кнопку регистрация
Тогда: Появляется всплывающее окно «Уважаемый пользователь, к сожалению такой логин уже есть в системе, используйте другой логин» с кнопкой ОК

**Регистрация пользователя с незаполненными логин, пароль, почтовый ящик**
Дано: Пользователь на странице регистрации
Когда: Пользователь вводит данные, но не заполняет обязательные поля(логин, почта пароль) и нажимает кнопку регистрация
Тогда: Появляется всплывающее окно «Уважаемый пользователь, для регистрации в системе, необходимо указать <Название(я) не заполненного поля>« с кнопкой ОК

**Comment by AleksandrKovalev186** [comment]
**Добавление/Удаление Книги**

**Добавление Книги в ручном режиме( не идёт запрос в API ISBN**)*
Дано: Зарегистрированный пользователь, на странице с книгами
Когда: Пользователь вводит название книги, и нажимает Кнопку «Добавить»
Тогда: На странице появляется Иконка с книгой (на иконке есть кнопка удалить и изменить)

**Удаление книги**
Дано: Зарегистрированный пользователь, на странице с книгами, у пользователя добавленна хотя бы одна книга
Когда: Пользователь нажимает на иконке с добавленной книгой на кнопку удалить
Тогда: Появляется всплывающее окно «Уважаемый <Логин> Вы действительно хотите удалить книгу <Название книги>« с кнопками ДА и НЕТ
И При нажатии НЕТ окно закрывается иконка с книгой остаётся на месте.
И При нажатии ДА окно закрывается, иконка с книгой пропадает со страницы пользователя

**Добавлении книги через API ISBN**
Дано: Зарегистрированный пользователь, на странице с книгами
Когда: Пользователь вводит ISBN книги, и нажимает Кнопку «Добавить»
Тогда: Уходит запрос в ISBN, и возвращается ответ с Данными
И Пользователю отображается диалоговое окно с данными о книге с тремя кнопками «Добавить книгу» и «Ввести ISBN еще раз» и «Ввести Название книги в ручную»
И При нажатии кнопки «Добавить» окно закрывается, иконка с книгой отображается на странице пользователя
И При нажатии кнопки «Ввести ISBN еще раз» окно закрывается, на страница пользователя  выделенно поле(сразу можно печатать) ISBN данные не удалены в поле.
И При нажатии кнопки «Ввести Название книги» окно закрылось,  на странице пользователя выделено поле «Название книги» в поле «ISBN»нет данных

**Comment by AleksandrKovalev186** [comment]
**Чтение Книги**

**Старт чтения книги**
Дано: Зарегистрированный пользователь, на странице с книгами, у пользователя добавлена хотя бы одна книга,  в статус «Не начата»
Когда: Пользователь, нажимает на кнопку «Начать читать книгу»
Тогда: Всплывает окно в котором есть 2 поля,**1** поле (сколько страниц прочитано, по умолчанию 0) **2**  Количество страниц в книге, необходимо указать количество страниц в книге( если книгу получили по ISBN то стоит количество страниц оттуда, но поле редактируемое) с кнопкой «Начать»
И при заполнении количества страниц и нажатии кнопки «Начать» окно закрывается книга меняет статус на «В процессе» отображается сколько страниц прочитано.
—Следует отметить что пользователь может не вводить количество страниц и нажать «Начать» окно должно закрыться но на значке с книгой будет сообщение, напоминающее о том что нужно ввести количество страниц статус «Ожидание».

**Сколько прочитано страниц в книге**
Дано: Зарегистрированный пользователь, на странице с книгами, у пользователя добавлена хотя бы одна книга, которая находится в статусе «В процессе»
Когда: Пользователь нажимает на книгу
Тогда: Всплывает окно с полем «Сколько прочитано?» и кнопкой «ОК»
И когда пользователь вводит количество и нажимает «ОК» 
И то число мы прибавляем к уже прочитанным страницам(по умолчанию 0)
Изменяется шкала прогресса данной книги
Пояснение если пользователь ничего не ввёл и нажал «ОК» то прибавим 0
Если количество прочитанных больше общего количества страниц, то переведём книгу в статус «Прочитана»

**Comment by AleksandrKovalev186** [comment]
**Статусы для книг**

**«Не начата»**
Книга добавлена но еще пользователь не приступил к чтению

**«Ожидание»**
Пользователь начал читать но мы не можем ее оценить, так как не введено общее количество страниц

**«В процессе»** 
Пользователь. Начал читать, страницы введены

**«На паузе»** 
Пользователь решил остановить чтение(под это сделаем кнопку) так как нужно эти книги убирать с главной страницы во вкладку «На паузе»

**«Прочитана»**
Пользователь дочитал книгу количество прочитанных страниц в книге больше или равно общему количеству страниц (книга исчезает с главной страницы и попадает во вкладку «Архив»

**Comment by GSkoba** [comment]
@AleksandrKovalev186 ты все так хорошо расписал, что наверное даже нечего добавить. Предлагаю придерживаться этого сценария и закрыть таск, если возникнут идеи будем обсуждать в рамках конкретных таск.
