### ISSUE TITLE
ТЗ (READ.ME)

### ISSUE THREAD

**Issue by GSkoba** [baltic-guys/read-path#4]
PART 1

**Comment by GSkoba** [comment]
1. Витрина книг (Книжная полка - шарить свой лист)
2. Timeline / roadmap 
    1.  https://codepen.io/wdmg/pen/ZWmwNM
    2.  https://codepen.io/abosarge/pen/PzBXrd
    3.  https://codepen.io/meuequalsd/pen/YLdwyj
    4.  https://codepen.io/logiccanvas-the-lessful/pen/ExjPKmx
3. Трекинг активности чтения книг и сопутствующие метрики (можно через телеграмм бота / apple watch  заносить данные)
4. Доп информация по книги
5. Подбор книг через регрессии 
6. Нотификации / напоминание / тренер чтения)

**Comment by perelygina** [comment]
Но это не похоже на PART 1

**Comment by unStatiK** [comment]
Добавлю

1. Book challenge 

По таймлайну я бы хотел видеть, что-то типо такого http://almende.github.io/chap-links-library/timeline.html (не по внешнему виду, а по принципу)

**Comment by AleksandrKovalev186** [comment]
Вопрос по 3 пункту. Будем как-то сравнивать пользователя с другими пользователями приложения? Например вы прочитали 30 страниц, что на 20 процентов меньше среднего. Или пользователь, А оставил рецензию на прочитанную книгу, мы даём ее другим пользователям, они ставят лайки, мы повышаем приоритет пользователя. Тип как в Буквоеде(там еще он увеличивается на основе прочитанных книг)

**Comment by AleksandrKovalev186** [comment]
Также вопрос будем давать ссылки на магазины в которых можно книги которые мы советуем купить?

**Comment by GSkoba** [comment]
> Также вопрос будем давать ссылки на магазины в которых можно книги которые мы советуем купить?

Можно попробовать прикрутить какой нибудь поиск, но это пока какие то очень далекие планы. @perelygina правильно говорит что нам надо хотя бы начать с малого)

**Comment by GSkoba** [comment]
> Вопрос по 3 пункту. Будем как-то сравнивать пользователя с другими пользователями приложения? Например вы прочитали 30 страниц, что на 20 процентов меньше среднего. Или пользователь, А оставил рецензию на прочитанную книгу, мы даём ее другим пользователям, они ставят лайки, мы повышаем приоритет пользователя. Тип как в Буквоеде(там еще он увеличивается на основе прочитанных книг)

Сравнивать пользователей наверное так себе, я больше это вижу как тренер для чтения: есть какой то набор книг которые полезно прочитать, но человеку тяжело собраться и вот он начинает с того что читает в день по 10 стр/ 10 мин/ 1 глава, ему отправляются нотификации и тип ты молодец или на оборот ты 💩 почитай книжку. По второй часте вопроса можно много чего накрутить.

**Comment by GSkoba** [comment]
Определение книги по идентификатору

**Comment by GSkoba** [comment]
> Определение

https://www.triumph.ru/html/serv/poisk-isbn.html
